name: chessalyst
description: A pgn viewer to view and analyze chess games.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  yaru: ^8.1.0
  go_router: ^16.0.0
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  handy_window: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true